### ISSUE TITLE
Unable to download dataset

### ISSUE THREAD

**Issue by kfmn** [IS2AI/Uzbek_ASR#1]
Hi,

I've tried to download dataset but when clicking "Download data" folder I see only Google Form and after filling and submittiing it nothing occurs.
Please fix the downloading scenario.

Best regards, Max

**Comment by mussakhojayeva** [comment]
Hi Max, 
Distribution started couple of days ago. Please notify me if you did not receive the dataset.

**Comment by craigbaker** [comment]
Hello, I'm also unable to download the data. I tried earlier in August, and again today. I enter my data in the google form, click Submit, and it says "Your response has been recorded." but no further information on how to download the data. Regards -Craig

**Comment by mussakhojayeva** [comment]
> Hello, I'm also unable to download the data. I tried earlier in August, and again today. I enter my data in the google form, click Submit, and it says "Your response has been recorded." but no further information on how to download the data. Regards -Craig

Hi, a reply to your today's request has been sent. We could not find any request dated in August though.
